/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by gensrv_cpp from file /home/pioneer/group41/src/hippo2/srv/Int.srv
 *
 */


#ifndef HIPPO2_MESSAGE_INT_H
#define HIPPO2_MESSAGE_INT_H

#include <ros/service_traits.h>


#include <hippo2/IntRequest.h>
#include <hippo2/IntResponse.h>


namespace hippo2
{

struct Int
{

typedef IntRequest Request;
typedef IntResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Int
} // namespace hippo2


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::hippo2::Int > {
  static const char* value()
  {
    return "19aac5e823802d733295ea3ec20e6350";
  }

  static const char* value(const ::hippo2::Int&) { return value(); }
};

template<>
struct DataType< ::hippo2::Int > {
  static const char* value()
  {
    return "hippo2/Int";
  }

  static const char* value(const ::hippo2::Int&) { return value(); }
};


// service_traits::MD5Sum< ::hippo2::IntRequest> should match 
// service_traits::MD5Sum< ::hippo2::Int > 
template<>
struct MD5Sum< ::hippo2::IntRequest>
{
  static const char* value()
  {
    return MD5Sum< ::hippo2::Int >::value();
  }
  static const char* value(const ::hippo2::IntRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::hippo2::IntRequest> should match 
// service_traits::DataType< ::hippo2::Int > 
template<>
struct DataType< ::hippo2::IntRequest>
{
  static const char* value()
  {
    return DataType< ::hippo2::Int >::value();
  }
  static const char* value(const ::hippo2::IntRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::hippo2::IntResponse> should match 
// service_traits::MD5Sum< ::hippo2::Int > 
template<>
struct MD5Sum< ::hippo2::IntResponse>
{
  static const char* value()
  {
    return MD5Sum< ::hippo2::Int >::value();
  }
  static const char* value(const ::hippo2::IntResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::hippo2::IntResponse> should match 
// service_traits::DataType< ::hippo2::Int > 
template<>
struct DataType< ::hippo2::IntResponse>
{
  static const char* value()
  {
    return DataType< ::hippo2::Int >::value();
  }
  static const char* value(const ::hippo2::IntResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HIPPO2_MESSAGE_INT_H
